if(0, "0 is true" println, "0 is false" println)
if(false, "false is true" println, "false is false" println)
if(nil, "nil is true" println, "nil is false" println)
if(true, "true is true" println, "true is false" println)
if("", "empty string is true" println, "empty string is false" println)